name: FER Project Pipeline

on:
  push:
    branches: [ "main" ] # Runs every time you push to the main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verify Project Structure
      run: |
        # This checks if your essential files are in the right place
        ls app.py
        ls emotion_class.h5
        ls templates/index.html

    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
